const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const fs = require('fs/promises');
function pick(obj,keys,fallback=null){if(!obj||typeof obj!=='object')return fallback;for(const k of keys)if(obj[k]!==undefined&&obj[k]!==null)return obj[k];return fallback}
function arr(v){return Array.isArray(v)?v:[]}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function normalize(parsed){const root=parsed?.replay||parsed?.data||parsed||{};const rawPlayers=arr(root.PlayerData).length?root.PlayerData:arr(root.playerData).length?root.playerData:arr(root.players).length?root.players:arr(root.Players);const durationMs=num(pick(root,['lengthInMs','LengthInMs','length_in_ms'],0));const duration=durationMs?durationMs/1000:num(pick(root,['duration','Duration'],0));const players=rawPlayers.map((p,i)=>{const name=pick(p,['PlayerName','playerName','Name','name','PlayerNameCustomOverride','StreamerModeName'],`PLAYER_${i+1}`);const cosmetics=p?.Cosmetics||{};const locs=arr(p.Locations);const last=locs[locs.length-1]||{};const rep=pick(last,['ReplicatedMovement','replicatedMovement'],{})||{};const loc=pick(rep,['Location','location'],{})||{};const x=num(pick(loc,['X','x'],0)),y=num(pick(loc,['Y','y'],0));return[String(name),num(pick(p,['Kills','kills'],0)),String(pick(cosmetics,['Character','HeroType','Parts'],'Unknown')||'Unknown'),100,0,Math.max(.05,Math.min(.95,.5+x/50000)),Math.max(.05,Math.min(.95,.5+y/50000))]});const rawEvents=arr(root.Eliminations).length?root.Eliminations:arr(root.eliminations).length?root.eliminations:arr(root.events).length?root.events:arr(parsed?.events);const events=rawEvents.map((e,i)=>[num(pick(e,['Time','time','StartTime','startTime','Timestamp','timestamp'],i)),String(pick(e,['Killer','killer','KillerName','killerName','Eliminator','eliminator'],'Unknown')),String(pick(e,['Victim','victim','Eliminated','eliminated','EliminatedName','eliminatedName'],'Unknown')),String(pick(e,['Weapon','weapon','WeaponName','weaponName','Item','item'],'Unknown weapon'))]).sort((a,b)=>a[0]-b[0]);const finalDuration=Math.max(1,Math.ceil(duration||(events.length?Math.max(...events.map(e=>e[0]))+30:1200)));return{duration:finalDuration,players,events,playerCount:players.length,totalKills:events.length||players.reduce((a,p)=>a+p[1],0)}}
ipcMain.handle('parse-replay',async(_event,filePath)=>{try{if(!filePath)throw new Error('No replay selected.');const parser=require('fortnite-replay-parser');const parsed=await parser(await fs.readFile(filePath),{parseLevel:10,debug:false});return{normalized:normalize(parsed)}}catch(err){return{error:err?.stack||err?.message||String(err)}}});
function attachLocalImporter(win){win.webContents.executeJavaScript(`(()=>{if(window.__localImporterInstalled)return;window.__localImporterInstalled=true;const input=document.querySelector('#file');if(!input)return;input.addEventListener('change',async(ev)=>{const file=ev.target.files&&ev.target.files[0];if(!file||!window.replayAPI)return;const name=document.querySelector('#fileName');if(name)name.textContent=file.name;try{const result=await window.replayAPI.parseFile(file.path);if(result.error)throw new Error(result.error);const d=result.normalized;if(Array.isArray(window.P)&&Array.isArray(d.players)){P.splice(0,P.length,...d.players);if(typeof roster==='function')roster()}if(Array.isArray(window.E)&&Array.isArray(d.events)){E.splice(0,E.length,...d.events);if(typeof feed==='function')feed()}const slider=document.querySelector('#timeline');if(slider){slider.max=String(d.duration);slider.value='0'}if(typeof t!=='undefined')t=0;const durationLabel=String(Math.floor(d.duration/60)).padStart(2,'0')+':'+String(Math.floor(d.duration%60)).padStart(2,'0');const statSection=document.querySelectorAll('section')[1];if(statSection){const cells=statSection.querySelectorAll('div.flex-col');if(cells.length>=5){cells[1].querySelector('b').textContent=String(d.playerCount||d.players.length);cells[3].querySelector('b').textContent=String(d.totalKills||d.events.length);cells[4].querySelector('b').textContent=durationLabel}}const clock=document.querySelector('#clock');if(clock)clock.textContent='00:00 / '+durationLabel;if(typeof draw==='function')draw();window.__localReplayDuration=d.duration;if(window.__localReplayClockTimer)clearInterval(window.__localReplayClockTimer);window.__localReplayClockTimer=setInterval(()=>{const c=document.querySelector('#clock');if(c&&typeof t!=='undefined'){const f=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0');c.textContent=f(t)+' / '+durationLabel}},100)}catch(err){alert('Could not decode this replay.\\n\\n'+(err.message||err))}},true)})()`,true).catch(()=>{})}
function createWindow(){const win=new BrowserWindow({width:1500,height:950,minWidth:1100,minHeight:700,backgroundColor:'#080b10',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'index.html'));win.webContents.once('did-finish-load',()=>attachLocalImporter(win))}
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});